###Rooms Index
GET http://localhost:3000/rooms.json

###Rooms Create
POST http://localhost:3000/rooms.json
Content-Type: application/json

{
  "name" : "Hallway 2",
  "bgimage" : "Image of room goes here"
}

###Rooms Show
GET http://localhost:3000/rooms/1.json


###Rooms Update
PATCH http://localhost:3000/rooms/1.json
Content-Type: application/json

{
  "bgimage": "On image goes here"
}
