@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTA2NTQxMTF9.CXDF8nVThd6saSNHOASJP9-91YOo-MvXrsNmoycLUK4

###Tasks Index
GET http://localhost:3000/tasks.json

###Tasks Create
POST http://localhost:3000/tasks.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Move Furniture",
  "description": "Move TV stand to west wall, re-align couches/seats/tables square to tv stand",
  "user_id": 2,
  "room_id": 3
}

###Tasks Show
GET http://localhost:3000/tasks/1.json

###Tasks Update
PATCH http://localhost:3000/tasks/1.json
Content-Type: application/json

{
  "task.title": "title",
  "task.description": "description",
  "task.user_id": "user_id",
  "task.room_id": "room_id"
}
