@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTA2NTk4MjV9.h8LSXoa0RyKhgSk0lKwDRlnvGpSk5lVVsW8Mo3FRRd4

###Tasks Index
GET http://localhost:3000/tasks.json

###Tasks Create
POST http://localhost:3000/tasks.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Move Furniture",
  "description": "Move TV stand to west wall, re-align couches/seats/tables square to tv stand",
  "user_id": 2,
  "room_id": 3
}

###Tasks Show
GET http://localhost:3000/tasks/1.json

###Tasks Update
PATCH http://localhost:3000/tasks/2.json
Content-Type: application/json

{
  "title": "something else",
  "description": "description",
  "user_id": "1",
  "room_id": "2"
}
