###Tasks Index
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTA2NTQxMTF9.CXDF8nVThd6saSNHOASJP9-91YOo-MvXrsNmoycLUK4
GET http://localhost:3000/tasks.json

###Tasks Create
POST http://localhost:3000/tasks.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Clean Room",
  "description": "Pick up clothes, vacuum, bring out dirty dishes",
  "user_id": 1,
  "room_id": 1
}

###Tasks Show
GET http://localhost:3000/tasks/1.json

###Tasks Update
PATCH http://localhost:3000/tasks/1.json
Content-Type: application/json

{
  "task.title": "title",
  "task.description": "description",
  "task.user_id": "user_id",
  "task.room_id": "room_id"
}
