### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "user4",
  "email": "user4@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users Index
GET http://localhost:3000/users.json

### Users Show
GET http://localhost:3000/users/1.json